### ISSUE TITLE
这个问题要怎么解决？

### ISSUE THREAD

**Issue by LSpirit828** [yerfor/GeneFacePlusPlus#147]
(geneface) E:\GeneFace++>python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 --force_single_process
todo videos number: 1
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
| Extracting Segmaps && Saving...
generating segment images in single-process...: 0it [00:00, ?it/s]
| Extracted Segmaps Done.
| Extracting background...
<class 'AssertionError'>
Traceback (most recent call last):
  File "E:\GeneFace++\data_gen\utils\process_video\extract_segment_imgs.py", line 361, in extract_segment_job
    bg_img = extract_background(img_lst, segmap_mask_lst, method=background_method, device=device, mix_bg=mix_bg)
  File "E:\GeneFace++\data_gen\utils\process_video\extract_segment_imgs.py", line 74, in extract_background
    assert len(img_lst) > 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\GeneFace++\data_gen\utils\process_video\extract_segment_imgs.py", line 491, in <module>
    extract_job(*fn_args[0])
  File "E:\GeneFace++\data_gen\utils\process_video\extract_segment_imgs.py", line 384, in extract_segment_job
    traceback.print_exc(e)
  File "C:\ProgramData\anaconda3\envs\geneface\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\ProgramData\anaconda3\envs\geneface\lib\traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "C:\ProgramData\anaconda3\envs\geneface\lib\traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "C:\ProgramData\anaconda3\envs\geneface\lib\traceback.py", line 357, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'AssertionError' and 'int'

**Comment by pxssw** [comment]
是不是推理阶段，如果是排查一下你的音频时长是否大于视频时长

**Comment by LSpirit828** [comment]
> 是不是推理阶段，如果是排查一下你的音频时长是否大于视频时长
是提取语义处理图片，提取图像，segmap和背景这一步

**Comment by Anleeos** [comment]
提取背景失败了，你的视频需要保证每一帧的背景都是大致相同的，如果有几处背景不一样就会在这个阶段报错

**Comment by XinBow99** [comment]
Windows or linux?

**Comment by mnbv7758** [comment]
我也是同样的问题，在windows11下

**Comment by kkkwjr** [comment]
(geneface) root@autodl-container-883c4da55e-0f4413f7:~/autodl-tmp/GeneFacePlusPlus-main# python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 # extract image, segmap, and background
todo videos number: 1
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1715754318.335415   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.360974   37577 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.67), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1715754318.394217   37580 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
/root/miniconda3/envs/geneface/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024.
  graph_config = self._runner.get_graph_config()
| Extracting Segmaps && Saving...
generating segment images in multi-processes...:   0%|               | 0/1700 [00:00<?, ?it/s]I0000 00:00:1715754318.485512   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.546476   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.546577   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.546577   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.547141   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
free(): invalid pointer
I0000 00:00:1715754318.547712   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.550985   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.551983   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.552576   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.552976   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.553024   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.553727   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.554492   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.555206   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
free(): invalid pointer
I0000 00:00:1715754318.560020   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.646444   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer

**Comment by kkkwjr** [comment]
(geneface) root@autodl-container-883c4da55e-0f4413f7:~/autodl-tmp/GeneFacePlusPlus-main# python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 # extract image, segmap, and background
todo videos number: 1
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1715754318.335415   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.360974   37577 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.67), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
W0000 00:00:1715754318.394217   37580 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
/root/miniconda3/envs/geneface/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024.
  graph_config = self._runner.get_graph_config()
| Extracting Segmaps && Saving...
generating segment images in multi-processes...:   0%|               | 0/1700 [00:00<?, ?it/s]I0000 00:00:1715754318.485512   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.546476   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.546577   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.546577   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.547141   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
free(): invalid pointer
I0000 00:00:1715754318.547712   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.550985   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.551983   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.552576   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.552976   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.553024   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.553727   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.554492   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
I0000 00:00:1715754318.555206   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
free(): invalid pointer
I0000 00:00:1715754318.560020   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1715754318.646444   37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
free(): invalid pointer
有大佬知道这个是什么原因吗

**Comment by qbqwolf** [comment]
> (geneface) root@autodl-container-883c4da55e-0f4413f7:~/autodl-tmp/GeneFacePlusPlus-main# python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 # extract image, segmap, and background todo videos number: 1 WARNING: All log messages before absl::InitializeLog() is called are written to STDERR I0000 00:00:1715754318.335415 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.360974 37577 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.67), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2 INFO: Created TensorFlow Lite XNNPACK delegate for CPU. W0000 00:00:1715754318.394217 37580 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors. /root/miniconda3/envs/geneface/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024. graph_config = self._runner.get_graph_config() | Extracting Segmaps && Saving... generating segment images in multi-processes...: 0%| | 0/1700 [00:00<?, ?it/s]I0000 00:00:1715754318.485512 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.546476 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.546577 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.546577 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.547141 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer free(): invalid pointer I0000 00:00:1715754318.547712 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.550985 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.551983 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.552576 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.552976 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.553024 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.553727 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.554492 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.555206 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer free(): invalid pointer I0000 00:00:1715754318.560020 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.646444 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer 有大佬知道这个是什么原因吗



> (geneface) root@autodl-container-883c4da55e-0f4413f7:~/autodl-tmp/GeneFacePlusPlus-main# python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 # extract image, segmap, and background todo videos number: 1 WARNING: All log messages before absl::InitializeLog() is called are written to STDERR I0000 00:00:1715754318.335415 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.360974 37577 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.67), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2 INFO: Created TensorFlow Lite XNNPACK delegate for CPU. W0000 00:00:1715754318.394217 37580 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors. /root/miniconda3/envs/geneface/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024. graph_config = self._runner.get_graph_config() | Extracting Segmaps && Saving... generating segment images in multi-processes...: 0%| | 0/1700 [00:00<?, ?it/s]I0000 00:00:1715754318.485512 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.546476 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.546577 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.546577 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.547141 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer free(): invalid pointer I0000 00:00:1715754318.547712 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.550985 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.551983 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.552576 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.552976 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.553024 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.553727 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.554492 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.555206 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer free(): invalid pointer I0000 00:00:1715754318.560020 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.646444 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer 有大佬知道这个是什么原因吗



> (geneface) root@autodl-container-883c4da55e-0f4413f7:~/autodl-tmp/GeneFacePlusPlus-main# python data_gen/utils/process_video/extract_segment_imgs.py --ds_name=nerf --vid_dir=data/raw/videos/${VIDEO_ID}.mp4 # extract image, segmap, and background todo videos number: 1 WARNING: All log messages before absl::InitializeLog() is called are written to STDERR I0000 00:00:1715754318.335415 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.360974 37577 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.67), renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2 INFO: Created TensorFlow Lite XNNPACK delegate for CPU. W0000 00:00:1715754318.394217 37580 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors. /root/miniconda3/envs/geneface/lib/python3.9/site-packages/mediapipe/tasks/python/vision/image_segmenter.py:158: UserWarning: MessageFactory class is deprecated. Please use GetMessageClass() instead of MessageFactory.GetPrototype. MessageFactory class will be removed after 2024. graph_config = self._runner.get_graph_config() | Extracting Segmaps && Saving... generating segment images in multi-processes...: 0%| | 0/1700 [00:00<?, ?it/s]I0000 00:00:1715754318.485512 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.546476 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.546577 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.546577 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.547141 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer free(): invalid pointer I0000 00:00:1715754318.547712 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.550985 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.551983 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.552576 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.552976 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.553024 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.553727 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.554492 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer I0000 00:00:1715754318.555206 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer free(): invalid pointer I0000 00:00:1715754318.560020 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 I0000 00:00:1715754318.646444 37574 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5 free(): invalid pointer 有大佬知道这个是什么原因吗

同问

**Comment by ck167493** [comment]
> 提取背景失败了，你的视频需要保证每一帧的背景都是大致相同的，如果有几处背景不一样就会在这个阶段报错

我的背景是绿幕都能报这个错
