### ISSUE TITLE
RuntimeError: Invalid shape for input size during inference with nerf_keypoint_mode: lm468

### ISSUE THREAD

**Issue by Chichibabin** [yerfor/GeneFacePlusPlus#149]
I encountered a RuntimeError during the inference stage when using the parameter configuration `nerf_keypoint_mode: lm468`. The error occurs when trying to reshape an array in the `forward_audio2secc` method.

1. Train the model with the configuration `nerf_keypoint_mode: lm468`.
2. Run inference using the trained model.

```
Traceback (most recent call last):
File "genefacepp_infer.py", line 681, in <module>
GeneFace2Infer.example_run(inp)
File "genefacepp_infer.py", line 625, in example_run
infer_instance.infer_once(inp)
File "genefacepp_infer.py", line 275, in infer_once
out_name = self.forward_system(samples, inp)
File ".../lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "genefacepp_infer.py", line 610, in forward_system
self.forward_audio2secc(batch, inp)
File ".../lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(args, **kwargs)
File "genefacepp_infer.py", line 470, in forward_audio2secc
idexp_lm3d = idexp_lm3d.reshape([-1, 683])
RuntimeError: shape '[-1, 204]' is invalid for input of size 432432
```

**Comment by aso538** [comment]
I also encountered the same problem, have you solved it

**Comment by zuojianghua** [comment]
same problem

it seems assert keypoint_mode == 'lm68'
not ready for lm131 or lm468
