### ISSUE TITLE
ubprocess.CalledProcessError: Command '['python', 'data_gen/utils/process_video/extract_segment_imgs.py', '--ds_name=nerf', '--vid_dir=data/raw/videos/111.mp4']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by zhangjinyan888** [yerfor/GeneFacePlusPlus#173]
| Extracted Segmaps Done.
| Extracting background...
combining backgrounds...:   0%|                                                                  | 0/7 [00:00<?, ?it/s]
<class 'TypeError'> 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "E:\AI\GeneFacePlusPlus\data_gen\utils\process_video\extract_segment_imgs.py", line 363, in extract_segment_job
    bg_img = extract_background(img_lst, segmap_mask_lst, method=background_method, device=device, mix_bg=mix_bg)
  File "E:\AI\GeneFacePlusPlus\data_gen\utils\process_video\extract_segment_imgs.py", line 112, in extract_background
    bg = (segmap[0]).astype(bool) # [h,w] bool mask
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\GeneFacePlusPlus\data_gen\utils\process_video\extract_segment_imgs.py", line 493, in <module>
    extract_job(*fn_args[0])
  File "E:\AI\GeneFacePlusPlus\data_gen\utils\process_video\extract_segment_imgs.py", line 386, in extract_segment_job
    traceback.print_exc(e)
  File "E:\AI\GeneFacePlusPlus\python310\lib\traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "E:\AI\GeneFacePlusPlus\python310\lib\traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "E:\AI\GeneFacePlusPlus\python310\lib\traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "E:\AI\GeneFacePlusPlus\python310\lib\traceback.py", line 357, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'TypeError' and 'int'
Traceback (most recent call last):
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\AI\GeneFacePlusPlus\python310\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "E:\AI\GeneFacePlusPlus\inference\app_genefacepp.py", line 352, in b2
    subprocess.run(['python', process_video_script, '--ds_name=nerf', f'--vid_dir=data/raw/videos/{video_id}.mp4'], check=True)
  File "E:\AI\GeneFacePlusPlus\python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'data_gen/utils/process_video/extract_segment_imgs.py', '--ds_name=nerf', '--vid_dir=data/raw/videos/111.mp4']' returned non-zero exit status 1.

我是win系统，提示这个错误，能看下是哪里的原因吗

**Comment by zhangjinyan888** [comment]
linux 系统是正常的

**Comment by vincentrsr** [comment]
同样的问题，请问解决了吗
