### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/videos/juan/coeff_fit_mp.npy'

### ISSUE THREAD

**Issue by cs7p** [yerfor/GeneFacePlusPlus#224]
`export PYTHONPATH=./
export VIDEO_ID=juan
python data_gen/runs/binarizer_nerf.py --video_id=${VIDEO_ID}`

`/mnt/workspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py:213: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use import imageio.v2 as imageio or call imageio.v2.imread directly.
  ret_dict['bg_img'] = imageio.imread(background_img_name)
loading lm2d coeff ...
loading fitted 3dmm coeff ...
Traceback (most recent call last):
  File "/mnt/workspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py", line 338, in <module>
    binarizer.parse(video_id)
  File "/mnt/workspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py", line 317, in parse
    ret = load_processed_data(processed_dir)
  File "/mnt/workspace/GeneFacePlusPlus/data_gen/runs/binarizer_nerf.py", line 231, in load_processed_data
    coeff_dict = np.load(coeff_npy_name, allow_pickle=True).tolist()
  File "/root/miniconda3/envs/pytorch/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] **No such file or directory: 'data/processed/videos/juan/coeff_fit_mp.npy`**

**Comment by cs7p** [comment]
resolved, just remove --debug when running fit_3dmm_landmark.py
