### ISSUE TITLE
FileNotFoundError: No such file: 'GeneFacePlusPlus/data/processed/videos/xxxx/inpaint_torso_imgs/00006601.png'

### ISSUE THREAD

**Issue by zhangjunhao-scut** [yerfor/GeneFacePlusPlus#227]
| set_hparams Unknow hparams:  []
| Hparams chains:  ['egs/egs_bases/radnerf/base.yaml', 'egs/egs_bases/radnerf/lm3d_radnerf.yaml', 'egs/datasets/person_25_2_cropped/lm3d_radnerf.yaml', 'egs/datasets/person_25_2_cropped/lm3d_radnerf_sr.yaml']
| Hparams:  {
  "accumulate_grad_batches": 1,
  "add_eye_blink_cond": true,
  "ambient_coord_dim": 3,
  "ambient_loss_mode": "mae",
  "amp": true,
  "base_config": [
    "./lm3d_radnerf.yaml"
  ],
  "binary_data_dir": "data/binary/videos",
  "bound": 1,
  "camera_offset": [
    0,
    0,
    0
  ],
  "camera_scale": 4.0,
  "clip_grad_norm": 0.0,
  "clip_grad_value": 0,
  "cond_dropout_rate": 0.0,
  "cond_out_dim": 64,
  "cond_type": "idexp_lm3d_normalized",
  "cond_win_size": 1,
  "cuda_ray": true,
  "debug": false,
  "density_thresh": 10,
  "density_thresh_torso": 0.01,
  "desired_resolution": 2048,
  "dt_gamma": 0.00390625,
  "eval_max_batches": 100,
  "exp_name": "motion2video_nerf/person_25_2_cropped_head",
  "eye_blink_dim": 2,
  "far": 0.9,
  "finetune_lips": true,
  "finetune_lips_start_iter": 200000,
  "geo_feat_dim": 128,
  "grid_interpolation_type": "linear",
  "grid_size": 128,
  "grid_type": "tiledgrid",
  "gui_fovy": 21.24,
  "gui_h": 512,
  "gui_max_spp": 1,
  "gui_radius": 3.35,
  "gui_w": 512,
  "hidden_dim_ambient": 128,
  "hidden_dim_color": 128,
  "hidden_dim_sigma": 128,
  "individual_embedding_dim": 4,
  "individual_embedding_num": 13000,
  "infer": false,
  "infer_audio_source_name": "",
  "infer_bg_img_fname": "",
  "infer_c2w_name": "",
  "infer_cond_name": "",
  "infer_lm3d_clamp_std": 1.5,
  "infer_lm3d_lle_percent": 0.25,
  "infer_lm3d_smooth_sigma": 0.0,
  "infer_out_video_name": "",
  "infer_scale_factor": 1.0,
  "infer_smo_std": 0.0,
  "infer_smooth_camera_path": true,
  "infer_smooth_camera_path_kernel_size": 7,
  "init_method": "tcp",
  "lambda_ambient": null,
  "lambda_dual_fm": 0.0,
  "lambda_lap_ambient_loss": 0.0,
  "lambda_lpips_loss": 0.001,
  "lambda_weights_entropy": 0.0001,
  "load_ckpt": "",
  "load_imgs_to_memory": false,
  "log2_hashmap_size": 16,
  "lpips_mode": "vgg19_v2",
  "lpips_start_iters": 200000,
  "lr": 0.0005,
  "lr_lambda_ambient": 0.01,
  "max_ray_batch": 4096,
  "max_steps": 16,
  "max_updates": 250000,
  "min_near": 0.05,
  "n_rays": 65536,
  "near": 0.3,
  "nerf_keypoint_mode": "lm68",
  "not_save_modules": [
    "criterion_lpips",
    "dual_disc"
  ],
  "num_ckpt_keep": 1,
  "num_layers_ambient": 3,
  "num_layers_color": 2,
  "num_layers_sigma": 3,
  "num_sanity_val_steps": 2,
  "num_steps": 16,
  "num_valid_plots": 5,
  "optimizer_adam_beta1": 0.9,
  "optimizer_adam_beta2": 0.999,
  "polygon_face_mask": true,
  "print_nan_grads": false,
  "processed_data_dir": "data/processed/videos",
  "raw_data_dir": "data/raw/videos",
  "resume_from_checkpoint": 0,
  "save_best": true,
  "save_codes": [
    "tasks",
    "modules",
    "egs"
  ],
  "save_gt": true,
  "scheduler": "exponential",
  "seed": 9999,
  "smo_win_size": 3,
  "smooth_lips": false,
  "sr_start_iters": 0,
  "start_rank": 0,
  "target_ambient_loss": 1e-08,
  "task_cls": "tasks.radnerfs.radnerf_sr.RADNeRFTask",
  "tb_log_interval": 100,
  "torso_head_aware": false,
  "torso_individual_embedding_dim": 8,
  "torso_shrink": 0.8,
  "update_extra_interval": 16,
  "upsample_steps": 0,
  "use_window_cond": true,
  "val_check_interval": 2000,
  "valid_infer_interval": 10000,
  "valid_monitor_key": "val_loss",
  "valid_monitor_mode": "min",
  "validate": false,
  "video_id": "person_25_2_cropped",
  "warmup_updates": 0,
  "weight_decay": 0,
  "with_att": true,
  "with_sr": true,
  "work_dir": "checkpoints/motion2video_nerf/person_25_2_cropped_head",
  "world_size": -1,
  "zero_dummy": true
}
09/06 09:40:11 AM GPU available: True, GPU used: [1], world_size: 1, multi-machine training: False
/mnt/sdc1/jhzhang/GeneFacePlusPlus/tasks/radnerfs/dataset_utils.py:266: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.lm68s = torch.tensor(self.lm2ds[:, index_lm68_from_lm478, :])
val: Smooth head trajectory (rotation and translation) with a window size of 7
| Copied codes to checkpoints/motion2video_nerf/person_25_2_cropped_head/codes/20240906094026.
| cond_prenet Trainable Parameters: 0.050M
| blink_embedding Trainable Parameters: 0.000M
| blink_encoder Trainable Parameters: 0.001M
| cond_att_net Trainable Parameters: 0.004M
| position_embedder Trainable Parameters: 1.807M
| ambient_net Trainable Parameters: 0.029M
| ambient_embedder Trainable Parameters: 1.807M
| sigma_net Trainable Parameters: 0.041M
| direction_embedder Trainable Parameters: 0.000M
| color_net Trainable Parameters: 0.019M
| dropout Trainable Parameters: 0.000M
| sr_net Trainable Parameters: 0.271M
Sanity Val:   0%|                                       | 0/2 [00:00<?, ?step/s]
Traceback (most recent call last):
  File "/mnt/sdc1/jhzhang/GeneFacePlusPlus/utils/commons/trainer.py", line 236, in run_single_process
    self.train()
  File "/mnt/sdc1/jhzhang/GeneFacePlusPlus/utils/commons/trainer.py", line 314, in train
    self.evaluate(self.task, False, 'Sanity Val', max_batches=self.num_sanity_val_steps)
  File "/mnt/sdc1/jhzhang/GeneFacePlusPlus/utils/commons/trainer.py", line 276, in evaluate
    for batch_idx, batch in enumerate(pbar):
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/sdc1/jhzhang/GeneFacePlusPlus/tasks/radnerfs/dataset_utils.py", line 316, in __getitem__
    torso_img = load_image_as_uint8_tensor(self.samples[idx]['torso_img_fname'])
  File "/mnt/sdc1/jhzhang/GeneFacePlusPlus/utils/commons/image_utils.py", line 46, in load_image_as_uint8_tensor
    img = torch.as_tensor(imageio.imread(fname))
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/mnt/sdc1/jhzhang/anaconda3/envs/geneface/lib/python3.9/site-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/mnt/sdc1/jhzhang/GeneFacePlusPlus/data/processed/videos/person_25_2_cropped/inpaint_torso_imgs/00006601.png'

--------------------------------------------------------------------------------------------------------
数据处理的步骤一步步走完了，训练头部模型的时候反馈如下错误：
FileNotFoundError: No such file: '/mnt/sdc1/jhzhang/GeneFacePlusPlus/data/processed/videos/person_25_2_cropped/inpaint_torso_imgs/00006601.png'
找不到00006601.png，可是我的训练视频处理成图片集的时候，只有5610张，为什么程序会寻找不存在的图片。而且，训练头部模型的命令行我试了好几次，每次反馈同样的错误，都是找不到00006321.png，00006511,png这种不存在的图片。

**Comment by madonghui0329** [comment]
@zhangjunhao-scut 你的视频帧率不是25

**Comment by zhangjunhao-scut** [comment]
ok，我再去试试，感谢感谢
