### ISSUE TITLE
extract_segment_imgs 出现 Found array with 0 sample(s) 错误

### ISSUE THREAD

**Issue by husthzy** [yerfor/GeneFacePlusPlus#28]
请问可能是什么原因？
以下是具体错误：
todo videos number: 1
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1707117250.849784   20592 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1707117250.885737   20601 gl_context.cc:344] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 535.154.05), renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
| Extracting Segmaps && Saving...
generating segment images in single-process...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9768/9768 [43:22<00:00,  3.75it/s]
| Extracted Segmaps Done.
| Extracting background...
combining backgrounds...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 489/489 [03:02<00:00,  2.68it/s]
<class 'ValueError'> Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by NearestNeighbors.
Traceback (most recent call last):
  File "/home/hzy/code/GeneFacePlusPlus/data_gen/utils/process_video/extract_segment_imgs.py", line 361, in extract_segment_job
    bg_img = extract_background(img_lst, segmap_mask_lst, method=background_method, device=device, mix_bg=mix_bg)
  File "/home/hzy/code/GeneFacePlusPlus/data_gen/utils/process_video/extract_segment_imgs.py", line 139, in extract_background
    nbrs = NearestNeighbors(n_neighbors=1, algorithm='kd_tree').fit(fg_xys)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/site-packages/sklearn/base.py", line 1351, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/site-packages/sklearn/neighbors/_unsupervised.py", line 175, in fit
    return self._fit(X)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/site-packages/sklearn/neighbors/_base.py", line 518, in _fit
    X = self._validate_data(X, accept_sparse="csr", order="C")
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1026, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by NearestNeighbors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hzy/code/GeneFacePlusPlus/data_gen/utils/process_video/extract_segment_imgs.py", line 492, in <module>
    extract_job(*fn_args[0])
  File "/home/hzy/code/GeneFacePlusPlus/data_gen/utils/process_video/extract_segment_imgs.py", line 384, in extract_segment_job
    traceback.print_exc(e)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/traceback.py", line 179, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/traceback.py", line 119, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/traceback.py", line 502, in __init__
    self.stack = StackSummary.extract(
  File "/home/hzy/.conda/envs/geneface/lib/python3.10/traceback.py", line 357, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'ValueError' and 'int'

**Comment by husthzy** [comment]
似乎是分割算法未能找到前景像素？

**Comment by husthzy** [comment]
继续检查，发现head_imgs相比gt_imgs文件夹，少了3张图片，分别是第1张，第2张，以及最后一张：00000000.png，00000001.png，00009767.jpg
但是这3张图片相比其他图片来说并没有什么区别

**Comment by husthzy** [comment]
重新跑了一次，又正常了......

**Comment by vincentrsr** [comment]
重哪里开始重新跑的，遇到一摸一样的，重新执行命令也不行
