### ISSUE TITLE
New problems arise during file inference，config.yaml It exists but cannot be recognized. Why?

### ISSUE THREAD

**Issue by anmandsu** [yerfor/GeneFacePlusPlus#78]
| load 'model' from 'checkpoints/audio2motion_vae/model_ckpt_steps_400000.ckpt', strict=True
Traceback (most recent call last):
  File "/root/GeneFacePlusPlus/inference/app_genefacepp.py", line 224, in <module>
    demo = genefacepp_demo(
  File "/root/GeneFacePlusPlus/inference/app_genefacepp.py", line 130, in genefacepp_demo
    infer_obj = Inferer(
  File "/root/GeneFacePlusPlus/inference/genefacepp_infer.py", line 125, in __init__
    self.secc2video_model = self.load_secc2video(head_model_dir, torso_model_dir)
  File "/root/GeneFacePlusPlus/inference/genefacepp_infer.py", line 165, in load_secc2video
    set_hparams(f"{os.path.dirname(torso_model_dir) if os.path.isfile(torso_model_dir) else torso_model_dir}/config.yaml")
  File "/root/GeneFacePlusPlus/utils/commons/hparams.py", line 108, in set_hparams
    assert os.path.exists(args.config), args.config
AssertionError: motion2video_nerf/meee_torso/config.yaml

**Comment by yerfor** [comment]
set `--torso_ckpt` to `checkpoints/motion2video_nerf/xxx` instead of `motion2video_nerf/xxx`
