### ISSUE TITLE
验证部分，索引对不上是什么原因

### ISSUE THREAD

**Issue by zckcola** [yerfor/GeneFacePlusPlus#90]
1997step [04:07, 12.07step/s, ambient_loss=5.19e-6, head_psnr=24.1, lambda_ambient=89.4, lr_optimizer0_params_group0=0.000491, lr_optimizer0_params_group1=0.00491, l1999step [04:07, 12.18step/s, ambient_loss=5.19e-6, head_psnr=24.1, lambda_ambient=89.4, lr_optimizer0_params_group0=0.000491, lr_optimizer0_params_group1=0.00491, l1999step [04:07, 12.18step/s, ambient_loss=6.3e-6, density_grid_info_max_density=3.46e+5, density_grid_info_mean_density=4.04, density_grid_info_min_density=-1, density_grid_info_occupancy_rate=0.0329, density_grid_info_step_mean_count=320837, head_psnr=26.3, lambda_ambient=89.4, lr_optimizer0_params_group0=0.000491, lr_optimizeValid:   0%|                                                                                                                               | 0/100 [00:00<?, ?step/s]
Traceback (most recent call last):                                                                                                         | 0/100 [00:00<?, ?step/s]
  File "/root/autodl-tmp/GeneFacePlusPlus/utils/commons/trainer.py", line 236, in run_single_process
    self.train()
  File "/root/autodl-tmp/GeneFacePlusPlus/utils/commons/trainer.py", line 347, in train
    self.run_evaluation()
  File "/root/autodl-tmp/GeneFacePlusPlus/utils/commons/trainer.py", line 248, in run_evaluation
    eval_results = self.evaluate(self.task, test, tqdm_desc='Valid' if not test else 'test',
  File "/root/autodl-tmp/GeneFacePlusPlus/utils/commons/trainer.py", line 293, in evaluate
    output = task_ref.validation_step(*args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/GeneFacePlusPlus/tasks/radnerfs/radnerf_sr.py", line 344, in validation_step
    outputs['losses'], model_out = self.run_model(sample, infer=False)
  File "/root/autodl-tmp/GeneFacePlusPlus/tasks/radnerfs/radnerf_sr.py", line 202, in run_model
    model_out = self.model.render(rays_o, rays_d, cond_inp, bg_coords, poses, index=idx, staged=False, bg_color=bg_color, perturb=True, force_all_rays=False, cond_mask=cond_mask, eye_area_percent=eye_area_percent, **hparams)
  File "/root/autodl-tmp/GeneFacePlusPlus/modules/radnerfs/radnerf_sr.py", line 204, in render
    results = super().render(rays_o, rays_d, cond, bg_coords, poses, index, dt_gamma, bg_color, perturb, force_all_rays, max_steps, T_thresh, cond_mask, eye_area_percent=eye_area_percent, **kwargs)
  File "/root/autodl-tmp/GeneFacePlusPlus/modules/radnerfs/renderer.py", line 372, in render
    sigmas, rgbs, ambient = self.forward(xyzs, dirs, cond_feat, ind_code, cond_mask=cond_mask[rays_alive.bool()])
IndexError: The shape of the mask [33728] at index 0 does not match the shape of the indexed tensor [65536] at index 0
Terminated

**Comment by zckcola** [comment]
![image](https://github.com/yerfor/GeneFacePlusPlus/assets/145427194/a3c30cd4-8bc4-4844-bc8e-c267987e7177)
