### ISSUE TITLE
Inference ERROR: index 3389 is out of bounds for dimension 0 with size 3389

### ISSUE THREAD

**Issue by piwawa** [yerfor/GeneFacePlusPlus#92]
我训练的视频是2分15秒，用超过这个时间的音频（不管是wav还是mp3）都会报这个错，是不是不能用超过训练视频长度的音频推理？

**Comment by RayDean** [comment]
我遇到了同样的问题：
Traceback (most recent call last):
  File "/data/PyCodes/GeneFacePlusPlus/inference/genefacepp_infer.py", line 598, in <module>
    GeneFace2Infer.example_run(inp)
  File "/data/PyCodes/GeneFacePlusPlus/inference/genefacepp_infer.py", line 543, in example_run
    infer_instance.infer_once(inp)
  File "/data/PyCodes/GeneFacePlusPlus/inference/genefacepp_infer.py", line 201, in infer_once
    samples = self.prepare_batch_from_inp(inp)
  File "/data/PyCodes/GeneFacePlusPlus/inference/genefacepp_infer.py", line 263, in prepare_batch_from_inp
    ngp_pose = self.dataset.poses[i].unsqueeze(0)
IndexError: index 2025 is out of bounds for dimension 0 with size 2025

**Comment by luosiwu** [comment]
加上参数--drv_pose=0-2024即可：
使用mirror_index: 当索引序列且索引大于len_pose时获取镜像索引

**Comment by Chichibabin** [comment]
您好，请问我在添加--drv_pose= 参数后，视频渲染结束后会显示Killed，之后视频并没有保存到本地。我的执行的命令是：
```
python inference/genefacepp_infer.py --a2m_ckpt=checkpoints/audio2motion_vae --head_ckpt= --torso_ckpt=checkpoints/motion2video_nerf/may_torso --drv_aud=data/raw/val_wavs/input_audio_zh_long.wav --drv_pose=0-6072 --out_name=may_demo_long.mp4
```
